# Generated by Django 4.2.8 on 2024-02-09 07:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=10)),
                ('experience', models.CharField(max_length=16)),
                ('patient_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('consultation_fees', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('clinic_name', models.CharField(max_length=64)),
                ('clinic_website', models.CharField(max_length=128)),
                ('clinic_phone_number', models.CharField(max_length=16)),
                ('clinic_address', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True, max_length=2048, null=True)),
                ('added_by', models.CharField(default='Anonymous', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctordetails')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('hospital_name', models.CharField(max_length=256)),
                ('is_own_clinic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctordetails')),
            ],
        ),
    ]
