# Generated by Django 4.2.8 on 2024-02-09 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='diseases_can_treat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=30),
        ),
    ]
